#!/usr/bin/bash

# BASH script to list all machines in a project 

project=$1
server=$2

# Help
if [[ $1 == "help" || $1 == "Help" ]]; then
	echo "projectlist PROJECT"
	echo "projectlist PROJECT SERVER"
	exit
fi

if [[ -z $server ]]; then
	gcloud compute instances list --project $project
else
	gcloud compute instances list --project $project | grep $server
fi

