#!/usr/bin/bash

# Snapshot
# BASH script for creating standard and archive snapshots using the Google Cloud SDK
# By Nicholas Grogg

# Color variables
## Errors
red=$(tput setaf 1)
## Clear checks
green=$(tput setaf 2)
## User input required
yellow=$(tput setaf 3)
## Set text back to standard terminal font
normal=$(tput sgr0)


# Help function
function helpFunction(){
    printf "%s\n" \
    "Help" \
    "----------------------------------------------------" \
    " " \
    "help/Help" \
    "* Display this help message and exit" \
    " " \
    "standard/Standard" \
    "* Creates a standard snapshot" \
    "* Takes a hostname, purpose, intials and project as arguments" \
    "Usage, snapshot hostname purpose initials project" \
    "Ex. snapshot standard serverName wp ngg myProject" \
    " " \
    "archive/Archive" \
    "Creates an archive snapshot" \
    "Takes a hostname, purpose, and project as arguments" \
    "Usage, snapshots hostname purpose project" \
    "Ex. snapshot archive serverName storage myProject" \
    " "
}

# Function to create a standard snapshot
function createStandard(){
    printf "%s\n" \
    "Standard Snapshot" \
    "----------------------------------------------------"

    ## Store passed values
    server=$1
    purpose=$2
    initials=$3
    project=$4

    ## Variable validation
    if [[ -z $server ]] || [[ -z $purpose ]] || [[ -z $initials ]] || [[ -z $project ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Variable missing " \
        "----------------------------------------------------" \
        "Running help function and exiting." \
        "Re-run script with valid input${normal}"
        helpFunction
        exit 1
    fi

    ## Confirmation
    printf "%s\n" \
    "${yellow}IMPORTANT: Value Confirmation" \
    "----------------------------------------------------" \
    "Snapshot Type:" \
    "Standard" \
    "" \
    "Server: " "$server" \
    "" \
    "Purpose: " "$purpose" \
    "" \
    "Sysadmin: "  "$initials" \
    "" \
    "Project: "  "$project" \
    "" \
    "If all clear, press enter to proceed or ctrl-c to cancel${normal}"

    read junkInput

    ## Create snapshot
    ### Find server zone
    serverZone=$(gcloud compute instances list --project $project | grep $server | awk '{print $2}'| head -n 1)

    ### Find server disk
    diskName=$(gcloud compute disks list --project $project | grep $server | awk '{print $1}' | head -n 1)

    #TODO: Flag storage-location variable may need adjusted depending on needs
    ### Take snapsho
    gcloud compute disks snapshot $diskName --snapshot-names=$initials-$diskName-$purpose-$(date +"%Y%m%d") --storage-location=us --zone $serverZone --project $project

    ### Was snapshot taken successfully?
    if [[ $? = 0 ]]; then
        printf "%s\n" \
        "${green}Snapshot taken " \
        "----------------------------------------------------" \
        "Proceeding to validation ${normal}"
    else
        printf "%s\n" \
        "${red}ISSUE DETECTED - Something went wrong!" \
        "----------------------------------------------------" \
        "Exiting! ${normal}"
        exit 1
    fi

    ## Snapshot validation
    printf "%s\n" \
    "Snapshot Validation" \
    "----------------------------------------------------" \

    ### Get snapshot name
    snapshotName="$initials-$diskName-$purpose-$(date +"%Y%m%d")"

    ### Get size of snapshot
    snapshotSize=$(gcloud compute snapshots describe $snapshotName --project $project | grep storageBytes: | awk '{print $2}')

    ### Did command execute successfully?
    if [[ $? != 0 ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Gcloud command failed!" \
        "----------------------------------------------------" \
        "Exiting! ${normal}"
        exit 1
    fi

    ### Is snapshot empty at 0 B?
    if [[ "$snapshotSize" == "'0'" ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Snapshot size is 0 B!" \
        "----------------------------------------------------" \
        "Do not proceed with current work effort! " \
        " " \
        "Review disk and take snapshot manually" \
        " " \
        "Exiting! ${normal}"
        exit 1
    else
        printf "%s\n" \
        "${green}Snapshot size > 0 B" \
        "----------------------------------------------------" \
        "Proceed with work effort${normal}"
        exit 0
    fi

}

# Function to create an archive snapshot
function createArchive(){
    printf "%s\n" \
    "Archive Snapshot" \
    "----------------------------------------------------"

    ## Store passed values
    server=$1
    purpose=$2
    project=$3

    ## Variable validation
    if [[ -z $server ]] || [[ -z $purpose ]] || [[ -z $project ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Variable missing " \
        "----------------------------------------------------" \
        "Running help function and exiting." \
        "Re-run script with valid input${normal}"
        helpFunction
        exit 1
    fi

    ## Confirmation
    printf "%s\n" \
    "${yellow}IMPORTANT: Value Confirmation" \
    "----------------------------------------------------" \
    "Snapshot Type:" \
    "Archive" \
    "" \
    "Server: " "$server" \
    "" \
    "Purpose: " "$purpose" \
    "" \
    "Project: "  "$project" \
    "" \
    "Server should be powered off for best results!" \
    "" \
    "If all clear, press enter to proceed or ctrl-c to cancel${normal}"
    read junkInput

    ## Create snapshot
    ### Find server zone
    serverZone=$(gcloud compute instances list --project $project | grep $server | awk '{print $2}'| head -n 1)

    ### Find server disk
    diskName=$(gcloud compute disks list --project $project | grep $server | awk '{print $1}' | head -n 1)

    #TODO: Flag storage-location variable may need adjusted depending on needs
    ### Take snapshot
    gcloud compute snapshots create $diskName-$purpose-$(date +"%Y%m%d") --source-disk $diskName --storage-location=us --source-disk-zone $serverZone --project $project --snapshot-type ARCHIVE

    ### Was snapshot taken successfully?
    if [[ $? = 0 ]]; then
        printf "%s\n" \
        "${green}Snapshot taken " \
        "----------------------------------------------------" \
        "Moving to validation ${normal}"
    else
        printf "%s\n" \
        "${red}ISSUE DETECTED - Something went wrong!" \
        "----------------------------------------------------" \
        "Exiting! ${normal}"
        exit 1
    fi

    ## Snapshot validation
    printf "%s\n" \
    "Snapshot Validation" \
    "----------------------------------------------------" \

    ### Get snapshot name
    snapshotName="$diskName-$purpose-$(date +"%Y%m%d")"

    ### Get size of snapshot
    snapshotSize=$(gcloud compute snapshots describe $snapshotName --project $project | grep storageBytes: | awk '{print $2}')

    ### Did command execute successfully?
    if [[ $? != 0 ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Gcloud command failed!" \
        "----------------------------------------------------" \
        "Exiting! ${normal}"
        exit 1
    fi

    ### Is snapshot empty at 0 B?
    if [[ "$snapshotSize" == "'0'" ]]; then
        printf "%s\n" \
        "${red}ISSUE DETECTED - Snapshot size is 0 B!" \
        "----------------------------------------------------" \
        "Do not proceed with current work effort! " \
        "Exiting! ${normal}"
        exit 1
    else
        printf "%s\n" \
        "${green}Snapshot size > 0 B" \
        "----------------------------------------------------" \
        "Proceed with work effort${normal}"
        exit 0
    fi

}

# Main, read passed flags
printf "%s\n" \
"Snapshot" \
"----------------------------------------------------" \
"Checking flags passed" \
"----------------------------------------------------"

# Check passed flags
case "$1" in
[Hh]elp)
    printf "%s\n" \
    "Running Help function" \
    "----------------------------------------------------"
    helpFunction
    exit
    ;;
[Ss]tandard)
    printf "%s\n" \
    "Standard snapshot flag passed" \
    "----------------------------------------------------"
    createStandard $2 $3 $4 $5
    ;;
[Aa]rchive)
    printf "%s\n" \
    "Archive snapshot flag passed" \
    "----------------------------------------------------"
    createArchive $2 $3 $4
    ;;
*)
    printf "%s\n" \
    "${red}ISSUE DETECTED - Invalid input detected!" \
    "----------------------------------------------------" \
    "Running help function and exiting." \
    "Re-run script with valid input${normal}"
    helpFunction
    exit 1
    ;;
esac
